const DEPLOYMENT_STEP = {
  VERIFICATION: "VERIFICATION",
  CONFIG_LOOKUP: "CONFIG_LOOKUP",
  LOCK: "LOCK",
  DEPLOY_STEP: "DEPLOY_STEP",
  HEALTH_CHECK: "HEALTH_CHECK",
  RELEASE: "RELEASE",
};

const DEPLOYMENT_STATUS = {
  IN_PROGRESS: "IN_PROGRESS",
  SUCCESS: "SUCCESS",
  FAILED: "FAILED",
  SKIPPED: "SKIPPED",
};

const STATUS = {
  SUCCESS: "SUCCESS",
  FAILED: "FAILED",
};

const DEPLOYMENT_TYPE = {
  LOCAL: "LOCAL",
  REMOTE: "REMOTE",
};

module.exports = {
  DEPLOYMENT_STEP,
  DEPLOYMENT_TYPE,
  STATUS,
  DEPLOYMENT_STATUS,
};
